// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import ClassicLayout from './ClassicLayout.vue'
import Container from './Container.vue'

// Export components individually
export { ClassicLayout, Container }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('ClassicLayout', ClassicLayout)
  Vue.component('Container', Container)
}

// Export the library as a plugin
export default { install: install }
