// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import AButton from './AButton.vue'
import AContainer from './AContainer.vue'
import AInput from './AInput.vue'
import ASidebarItem from './ASidebarItem.vue'
import ClassicLayout from './ClassicLayout.vue'

// Export components individually
export { AButton, AContainer, AInput, ASidebarItem, ClassicLayout }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('AButton', AButton)
  Vue.component('AContainer', AContainer)
  Vue.component('AInput', AInput)
  Vue.component('ASidebarItem', ASidebarItem)
  Vue.component('ClassicLayout', ClassicLayout)
}

// Export the library as a plugin
export default { install: install }
