// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import AButton from './AButton.vue'
import AContainer from './AContainer.vue'
import ADatepicker from './ADatepicker.vue'
import AFileInput from './AFileInput.vue'
import AInput from './AInput.vue'
import APanelTitle from './APanelTitle.vue'
import ASidebarItem from './ASidebarItem.vue'
import ATextEditor from './ATextEditor.vue'
import ATitle from './ATitle.vue'
import ClassicLayout from './ClassicLayout.vue'

// Export components individually
export { AButton, AContainer, ADatepicker, AFileInput, AInput, APanelTitle, ASidebarItem, ATextEditor, ATitle, ClassicLayout }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('AButton', AButton)
  Vue.component('AContainer', AContainer)
  Vue.component('ADatepicker', ADatepicker)
  Vue.component('AFileInput', AFileInput)
  Vue.component('AInput', AInput)
  Vue.component('APanelTitle', APanelTitle)
  Vue.component('ASidebarItem', ASidebarItem)
  Vue.component('ATextEditor', ATextEditor)
  Vue.component('ATitle', ATitle)
  Vue.component('ClassicLayout', ClassicLayout)
}

// Export the library as a plugin
export default { install: install }
